title:             "Modest Study"
email:              "imbc0224@gmail.com"
description:        "keep going"
author:             "iheese"
baseurl:            
url:                "https://iheese.github.io"

# Social Profiles
#twitter_username:   SBootstrap
#github_username:    StartBootstrap
#facebook_username:  StartBootstrap
#instagram_username:  StartBootstrap
#linkedin_username:  StartBootstrap

# Add your google-analytics ID here to activate google analytics
#google_analytics:   "UA-87997801-1" # out your google-analytics code
#google-site-verification: "U-TTuSYPqCSmQS7Zc4vOgcJH4t5L-yv3f-TKhM-HcaU"

# Build settings
markdown: kramdown
# kramdown:
#   input: GFM
highlighter: rouge

paginate: 10
paginate_path: /page:num/
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-paginate
#  - jekyll-sitemap

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

sass:
  style: compressed

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      mathjax: true
      
tipue_search:
  include:
    pages: false
  exclude:
    files: [search.html, tags.html, index.html]